# Generated by Django 2.2.1 on 2019-05-04 14:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('Age', models.FloatField()),
                ('Region', models.CharField(max_length=100)),
                ('Phone', models.CharField(max_length=20)),
                ('Type', models.CharField(choices=[('DEF', 'Student'), ('PRV', 'Instructor/Moderator')], default='DEF', max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=200)),
                ('Body', models.TextField()),
                ('positiveVotes', models.IntegerField()),
                ('negativeVotes', models.IntegerField()),
                ('Category', models.CharField(choices=[('phy', 'Physics'), ('che', 'Chemistry'), ('bio', 'Biology'), ('eng', 'English'), ('ara', 'Arabic'), ('his', 'History'), ('art', 'Arts'), ('ict', 'Computer science'), ('mth', 'Maths'), ('gen', 'General')], default='gen', max_length=3)),
                ('timeStamp', models.DateTimeField(auto_now_add=True)),
                ('Author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.User')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Body', models.CharField(max_length=400)),
                ('timeStamp', models.DateTimeField(auto_now_add=True)),
                ('Author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.User')),
                ('onArticle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Topic')),
            ],
        ),
    ]
