# Generated by Django 2.2.1 on 2019-05-04 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20190504_1712'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topic',
            name='Body',
            field=models.TextField(unique=True),
        ),
        migrations.AlterField(
            model_name='topic',
            name='Category',
            field=models.CharField(choices=[('phy', 'Physics'), ('che', 'Chemistry'), ('bio', 'Biology'), ('eng', 'English'), ('ara', 'Arabic'), ('his', 'History'), ('art', 'Arts'), ('ict', 'Computer science'), ('mth', 'Maths'), ('gen', 'General')], default='gen', max_length=3, unique=True),
        ),
        migrations.AlterField(
            model_name='topic',
            name='Title',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='Age',
            field=models.FloatField(unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='Name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='Phone',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='Region',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='Type',
            field=models.CharField(choices=[('DEF', 'Student'), ('PRV', 'Instructor/Moderator')], default='DEF', max_length=3, unique=True),
        ),
    ]
