# Generated by Django 2.2.1 on 2019-05-04 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20190505_0115'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topic',
            name='negativeVotes',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='topic',
            name='positiveVotes',
            field=models.IntegerField(default=0),
        ),
    ]
