# Generated by Django 2.2.1 on 2019-05-06 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20190505_0118'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='videoLink',
            field=models.URLField(blank=True, max_length=400),
        ),
    ]
