# Generated by Django 2.2.1 on 2019-05-06 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_topic_videolink'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topic',
            name='Title',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
